linux:
	clear
	gcc main.c -o ../sender

windows:
	clear
	###### x86_64-w64-mingw32-gcc main.c -lws2_32 -o ../sender.exe ######
	Sorry, Windows cross-compiling isn't supported yet :\\

gen:
	clear
	gcc gen-bmp.c -o ../generator
